/* 
 * Login Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CharacterInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CharacterInformationTests
    {
        // TODO uncomment below to declare an instance variable for CharacterInformation
        //private CharacterInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CharacterInformation
            //instance = new CharacterInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CharacterInformation
        /// </summary>
        [Test]
        public void CharacterInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CharacterInformation
            //Assert.IsInstanceOfType<CharacterInformation> (instance, "variable 'instance' is a CharacterInformation");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OwnerEmail'
        /// </summary>
        [Test]
        public void OwnerEmailTest()
        {
            // TODO unit test for the property 'OwnerEmail'
        }
        /// <summary>
        /// Test the property 'Map'
        /// </summary>
        [Test]
        public void MapTest()
        {
            // TODO unit test for the property 'Map'
        }

    }

}
